### PR TITLE
"player was kicked" -> "player was banned"

### PR DESCRIPTION
**Pull request by zUltimaPG3D**
"kicked" could make people think that the player can rejoin after being forced out of the lobby. "banned" on the other hand, which is what *does* happen, conveys that the player can *not* rejoin.
not a big change by any means but i still think that, with almost everything referring to it as a "ban" and it functioning as a temporary one until the lobby owner makes a new lobby, it can still help clear up a bit of confusion. 
(also sorry for the csproj commit :sob:)

### CODE REVIEW

**Comment by xzxADIxzx** [comment]
> (also sorry for the csproj commit 😭)

Why ._.

**Comment by zUltimaPG3D** [comment]
> Why ._.

i can't build without it, i don't want it to be a big issue for you or anyone else though

**Comment by xzxADIxzx** [comment]
Funny thing is that I can compile it even if I put a single random char there

**Comment by zUltimaPG3D** [comment]
dotnet on linux issue then. doesnt matter as much i guess

**Comment by xzxADIxzx** [comment]
Hey, did you tried to remove the HintPath tag and instead put its content to Include like this:
```
<Reference Include="lib\BepInEx.dll"></Reference>
<Reference Include="lib\0Harmony.dll"></Reference>
```

**Comment by xzxADIxzx** [comment]
This looks much better and it works for me, so does it for you?
image

**Comment by zUltimaPG3D** [comment]
wait, let me test

**Comment by zUltimaPG3D** [comment]
confirmed, works

**Comment by xzxADIxzx** [comment]
Good, I'll merge the pull then

**Pull request merged**
