### PR TITLE
Interpolating movement camera

### PR DESCRIPTION
**Pull request by Ardub92**
Need to test. Camera interpolation when starting or ending Emoji.

https://github.com/xzxADIxzx/Join-and-kill-em-together/assets/35745292/c13ebb11-e410-41c4-966c-d52aa488b0f5

### CODE REVIEW

**Comment by xzxADIxzx** [comment]
I wanted to add this from the very beginning, but I was too lazy, so thanks!

**Comment by xzxADIxzx** [comment]
1107 LINES OF CODE?! WHAT'S WRONG WITH YOU?

**Comment by Ardub92** [comment]
> 1107 LINES OF CODE?! WHAT'S WRONG WITH YOU?

This is interpolating functions, you can use them in future

**Comment by xzxADIxzx** [comment]
Dude, u'r crazy, no one do such things

**Comment by xzxADIxzx** [comment]
There is like... nothing to interpolate

**Comment by xzxADIxzx** [comment]
This don't even sounds like ha-ha-ha, it's like he-he-he

**Comment by Ardub92** [comment]
> There is like... nothing to interpolate

You can then choose which interpolation to use when animating, so you can leave it like that for now. If size is important to you, I can remove all unnecessary functions.

**Comment by xzxADIxzx** [comment]
Pls, use built-in Unity's interpolation if it's possible

**Comment by Ardub92** [comment]
> Pls, use built-in Unity's interpolation if it's possible

I tried searching online, but there is an alternative `Slerp()` that is only a single option. It is much easier to leave the necessary functions for interpolation than to look for one built into the engine.

**Comment by Ardub92** [comment]
Bruh, I need to fix current pull request, because I found bug. See camera spinning when animation is gone?

**Pull request closed without merging**
