### PR TITLE
Filipino Translation

### PR DESCRIPTION
**Pull request by Fraku37**
Musta pre

### CODE REVIEW

**Comment by xzxADIxzx** [comment]
oh, noice :3

**Comment by xzxADIxzx** [comment]
Are you a member of our Discord server?

**Comment by xzxADIxzx** [comment]
I'd like to add you to the translators team so I could ping you anytime

**Comment by Fraku37** [comment]
Yeah I'm in the server, username's "Fraku37".
Thanks!

**Pull request merged**
