### PR TITLE
Adding in portuguese translation

### PR DESCRIPTION
**Pull request by Poyozit0**
added translation for mine native language because why not

### CODE REVIEW

**Comment by xzxADIxzx** [comment]
Are you a member of our discord server?
What's your nickname?

**Comment by Poyozit0** [comment]
Yes, nickname is "poyozito"

**Comment by Poyozit0** [comment]
> Are you a member of our discord server? What's your nickname?
Yes, the nickname is "poyozito"

**Comment by Poyozit0** [comment]
> Are you a member of our discord server? What's your nickname?

Yes, the nickname is "poyozito"

**Pull request merged**
