### PR TITLE
portuguese ui changes

### PR DESCRIPTION
**Pull request by Poyozit0**

### CODE REVIEW

**Comment by xzxADIxzx** [comment]
Wdy did u put [SIZE_IN_PIXELS] everywhere ._.

**Comment by xzxADIxzx** [comment]
Anyway, I'll fix it once I merge the pull

**Comment by Poyozit0** [comment]
> Wdy did u put [SIZE_IN_PIXELS] everywhere ._.

Because a good chunk of text doesnt work very well without it

**Comment by xzxADIxzx** [comment]
I mean, you DON'T NEED [SIZE_IN_PIXELS], you just use [20] or [16]

**Comment by xzxADIxzx** [comment]
Oh and what's wrong with line 39?

**Comment by Poyozit0** [comment]
> Oh and what's wrong with line 39?

just typed the wrong accent on the letter "A", its supposed to be "CONEXÃO" instead of "CONEXÂO", just small mistype

**Comment by xzxADIxzx** [comment]
I mean... You also removed --

**Comment by Poyozit0** [comment]
> I mean... You also removed --

oh crap, i didnt accidentally sorry

**Pull request merged**
